apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: bitnami/memcached
        ports:
        - name: http
          protocol: TCP
          containerPort: 11211
      - name: memcached-exporter
        image: tianctrl/memcached_exporter
        ports:
        - name: exporter
          protocol: TCP
          containerPort: 9050
