apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  ports:
    - name: http
      port: 11211
      targetPort: 11211
      protocol: TCP
    - name: exporter
      port: 9050
      targetPort: 9050
      protocol: TCP
  selector:
    app: memcached